# Generated by Django 6.0.1 on 2026-01-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
